export const sampleShift = [
  {
    id: 360,
    shiftName: "شیفت صبح",
    dayNumber: 3,
    hourNumber: 10,
    status: true,
    shiftPattern: "24-48",
  },
  {
    id: 401,
    shiftName: "شیفت صبح",
    dayNumber: 3,
    hourNumber: 10,
    status: true,
    shiftPattern: "24-48",
  },
  {
    id: 150,
    shiftName: "شیفت صبح",
    dayNumber: 3,
    hourNumber: 10,
    status: true,
    shiftPattern: "24-48",
  },
  {
    id: 250,
    shiftName: "شیفت صبح",
    dayNumber: 3,
    hourNumber: 10,
    status: true,
    shiftPattern: "24-48",
  },
  {
    id: 600,
    shiftName: "شیفت صبح",
    dayNumber: 3,
    hourNumber: 10,
    status: true,
    shiftPattern: "24-48",
  },
  {
    id: 400,
    shiftName: "شیفت صبح",
    dayNumber: 3,
    hourNumber: 10,
    status: true,
    shiftPattern: "24-48",
  },
  {
    id: 100,
    shiftName: "شیفت صبح",
    dayNumber: 3,
    hourNumber: 10,
    status: true,
    shiftPattern: "24-48",
  },
  {
    id: 200,
    shiftName: "شیفت صبح",
    dayNumber: 3,
    hourNumber: 10,
    status: true,
    shiftPattern: "24-48",
  },
  {
    id: 300,
    shiftName: "شیفت صبح",
    dayNumber: 3,
    hourNumber: 10,
    status: true,
    shiftPattern: "24-48",
  },
];
